DROP TABLE BUILDING CASCADE CONSTRAINTS;

DROP TABLE COMPUTER CASCADE CONSTRAINTS;

DROP TABLE CPU CASCADE CONSTRAINTS;

DROP TABLE GPU CASCADE CONSTRAINTS;

DROP TABLE HDD CASCADE CONSTRAINTS;

DROP TABLE MONITOR CASCADE CONSTRAINTS;

DROP TABLE PRINTER CASCADE CONSTRAINTS;

DROP TABLE RAM CASCADE CONSTRAINTS;

DROP TABLE ROOM CASCADE CONSTRAINTS;

DROP TABLE SOFTWARE CASCADE CONSTRAINTS;

DROP TABLE SSD CASCADE CONSTRAINTS;

DROP TABLE "user" CASCADE CONSTRAINTS;

DROP TABLE USER_BUILDING CASCADE CONSTRAINTS;